kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# Master node
- role: control-plane
  extraPortMappings:
  - containerPort: 30888
    hostPort: 80
    protocol: TCP
  - containerPort: 30999
    hostPort: 443
    protocol: TCP
  - containerPort: 31111
    hostPort: 8080
    protocol: TCP
- role: worker
